server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false # Disable cache for development
  datasource:
    url: jdbc:mysql://localhost:3306/mentallwellness
    username: root
    password: Sosamala@567
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    'show-sql': true
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: tinyllama
